apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for the Eclipse aeriOS Benchmarking Tool
name: benchmarking-tool
type: application
version: 1.0.0
keywords:
  - ravaga-helm-chart-generator
  - aeriOS
  - management
  - framework
  - benchmarking
